name: flutter_kyc
description: A package for verifying KYC documents.
version: 0.0.1
homepage: https://github.com/muigaidaniel/flutter_kyc

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  image_cropper: ^3.0.0
  stacked_services: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
